# Generated by Django 5.1.6 on 2025-03-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_name_ky_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytwo',
            name='category_two',
        ),
    ]
