# Generated by Django 5.1.6 on 2025-03-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_categorytwo_category_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
