# Generated by Django 5.1.6 on 2025-03-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_categorytwo_category_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category_st',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
            preserve_default=False,
        ),
    ]
